### ISSUE TITLE
Note about having Venmo being default payment method in Amazon

### ISSUE THREAD

**Issue by joshjohanning** [jakehilborn/debbit#100]
I was receiving this error and thought the app was broke:

> ERROR: 2023-07-14 14:18:02,443 my_visa_amazon_gift_card_reload error: Traceback (most recent call last):
>   File "debbit.py", line 294, in web_automation_wrapper
>   File "/Users/abc/Repos/debbit-v2.1.4-macOS/program_files/merchants/amazon_gift_card_reload.py", line 170, in web_automation
>     raise Exception('Unable to find or unable to click on card that has last 4 digits matching config file card.')
> Exception: Unable to find or unable to click on card that has last 4 digits matching config file card.

But it turns out the checkout flow got disrupted because I linked my Venmo account to Amazon and set it as default payment method for a promotion. I removed Venmo from my amazon account and now the app works as normal. 

Suggest to update the Readme to note this.

**Comment by jakehilborn** [comment]
Yo Josh, what's up?! Funny seeing a familiar face on some random GitHub project. We attended that Madison intro to computer science semester program together. How have you been?

Tbh I'm surprised this application even works at all. Haven't updated it in a while now.

**Comment by joshjohanning** [comment]
@jakehilborn whatup! I do remember you, think of my surprise as well when I find something online from a former classmate 😄 

The repo mostly still works, so great job 🥂
