### ISSUE TITLE
Xfinity Login Error

### ISSUE THREAD

**Issue by btbkilla** [jakehilborn/debbit#56]
Having issues with xfinity login failing. Output is below. Is anyone else seeing this?

v2.1 Windows Traceback (most recent call last):
  File "debbit.py", line 294, in web_automation_wrapper
  File "C:\Users\Downloads\debbit-v2.1-win64\program_files\merchants\xfinity_bill_pay.py", line 48, in web_automation
    WebDriverWait(driver, 90).until(expected_conditions.element_to_be_clickable((By.ID, 'customAmount')))
  File "selenium\webdriver\support\wait.py", line 71, in until
  File "selenium\webdriver\support\expected_conditions.py", line 297, in __call__
  File "selenium\webdriver\support\expected_conditions.py", line 128, in __call__
  File "selenium\webdriver\support\expected_conditions.py", line 415, in _find_element
  File "selenium\webdriver\support\expected_conditions.py", line 411, in _find_element
  File "selenium\webdriver\remote\webdriver.py", line 978, in find_element
  File "selenium\webdriver\remote\webdriver.py", line 321, in execute
  File "selenium\webdriver\remote\errorhandler.py", line 242, in check_response
selenium.common.exceptions.NoSuchWindowException: Message: Browsing context has been discarded
![2021-05-07_15-09-19-196028_xfinity_bill_pay](https://user-images.githubusercontent.com/2191863/117498598-02897100-af48-11eb-82d2-c4133b8d6d85.png)
[2021-05-07_15-09-19-196028_xfinity_bill_pay.txt](https://github.com/jakehilborn/debbit/files/6443857/2021-05-07_15-09-19-196028_xfinity_bill_pay.txt)

**Comment by btbkilla** [comment]
Was setting this up on a new machine so I had the latest version of firefox 88.01 released 5/5/21. Went back to version 87 and this issue went away.
