### ISSUE TITLE
FileNotFoundError: "webdriver_prefs.json" does not exist in the path that the program is searching within

### ISSUE THREAD

**Issue by Superpigdots** [jakehilborn/debbit#80]
I am getting the following error now:

> FileNotFoundError: [Errno 2] No such file or directory: 'C:\\Users\\nicho\\AppData\\Local\\Temp\\_MEI49882\\selenium\\webdriver\\firefox\\webdriver_prefs.json'

Here is the full messaging though:

> debbit.py:509: DeprecationWarning: firefox_profile has been deprecated, please use an Options object
Exception in thread Thread-1:
Traceback (most recent call last):
  File "threading.py", line 932, in _bootstrap_inner
  File "threading.py", line 870, in run
  File "debbit.py", line 113, in burst_loop
  File "debbit.py", line 289, in web_automation_wrapper
  File "debbit.py", line 509, in get_webdriver
  File "selenium\webdriver\firefox\firefox_profile.py", line 61, in __init__
FileNotFoundError: [Errno 2] No such file or directory: 'C:\\Users\\nicho\\AppData\\Local\\Temp\\_MEI49882\\selenium\\webdriver\\firefox\\webdriver_prefs.json'

When I navigate to the "firefox" folder in this path, no "webdriver_prefs.json" file is present. No files at all are present. I have show hidden files selected.

**Comment by Superpigdots** [comment]
@jakehilborn any update on this issue? Also, now, since my last PC restart, I am seeing this error message:

ERROR: 2022-01-17 22:40:33,336 Unable to check for updates. Check https://github.com/jakehilborn/debbit/releases if interested.

Is this just a standard line that shows whenever I restart the program?

**Comment by Superpigdots** [comment]
@jakehilborn, I still have not heard back from you and the error happened again today with the latest automated burst request. Are you still maintaining this program?
